'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
let n=0; const ok=(name,fn)=>{fn();n++;console.log('  ✓ '+name);};
console.log('\n[v1.0.12 security and coaching audit]');
ok('admin API requires verified allowlisted account',()=>assert.match(read('api/admin.js'),/!user\.verified \|\| !cfg\.isAdminEmail/));
ok('admin page requires verified allowlisted account',()=>assert.match(read('server.js'),/!adminUser\.verified \|\| !cfg\.isAdminEmail/));
ok('review moderation has the same admin gate',()=>assert.match(read('api/reviews.js'),/!u\.verified \|\| !cfg\.isAdminEmail/));
ok('mobile trial enforces the permanent identity ledger',()=>assert.match(read('api/mobile.js'),/prefs\.trialUsedBy\(\{userId:u\.id,email:u\.email,phone:u\.phone,deviceId\}\)/));
ok('Google signup leaves the trial as a pending gift',()=>assert.match(read('api/auth.js'),/pending:true, days:commerce\.TRIAL_DAYS/));
ok('unsafe fake phone OTP is unavailable',()=>{const s=read('api/verify.js');assert.match(s,/تأكيد الهاتف غير متاح حاليا/);assert.doesNotMatch(s,/any 6-digit/);});
ok('Paymob selects the signed provider order',()=>{const s=read('api/pay.js');assert.match(s,/const ref = obj\.order && obj\.order\.id/);assert.match(s,/amountOk/);assert.match(s,/currencyOk/);assert.match(s,/is_refunded/);});
ok('PayPal validates captured amount currency and custom reference',()=>{const s=read('api/pay.js');assert.match(s,/r\.customId===meta\.orderRef/);assert.match(read('lib/pay-providers.js'),/settled\.amount\.currency_code/);});
const coach=require('../lib/coach-progression');
ok('upper compound uses a conservative 2.5 kg step',()=>assert.equal(coach.incFor('Bench Press'),2.5));
ok('lower compound can use a 5 kg step',()=>assert.equal(coach.incFor('Back Squat'),5));
ok('deload reduces both load and sets',()=>{const t=coach.nextTarget({name:'Bench Press',reps:'8-12',sets:5},[{weight:60,reps:10,ts:1}],{mweek:5,meso:5});assert.equal(t.weight,54);assert.equal(t.sets,3);});
ok('nutrition self-report is wired into Flutter',()=>{const s=read('mobile/lib/screens/meal_plan_screen.dart');assert.match(s,/_checkinCard\(\)/);assert.match(s,/submitCheckin/);});
console.log(`\n${n} passed, 0 failed`);
