'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.EF_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'ef-friends-api-'));process.env.EF_DATABASE_ENGINE='sqlite';process.env.PORT='0';
process.env.EF_ANDROID_CERT_SHA256='AA:BB:CC';
const server=require('../server'),database=require('../lib/db'),{issueToken}=require('../lib/auth');const sql=database.db,created=new Date().toISOString();
for(const [id,name] of [[21,'علي'],[22,'محمد'],[23,'عمر']])sql.prepare('INSERT INTO users(id,email,name,pass_hash,pass_salt,verified,created_at) VALUES(?,?,?,?,?,?,?)').run(id,`api${id}@test.local`,name,'x','y',1,created);
const start=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),end=new Date(Date.parse(start)+6*86400000).toISOString().slice(0,10);
async function req(method,route,body,user){const headers={'Content-Type':'application/json'};if(user)headers.Cookie='ef_session='+issueToken(user);const response=await fetch(`http://127.0.0.1:${server.address().port}${route}`,{method,headers,body:body==null?undefined:JSON.stringify(body)});return {status:response.status,data:await response.json()};}
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS',name);}
(async()=>{await new Promise(r=>server.listening?r():server.once('listening',r));let id,code;
 await test('authentication is required',async()=>assert.equal((await req('GET','/api/mobile/friend-challenges')).status,401));
 await test('invite web page and Android link verification are served',async()=>{const page=await fetch(`http://127.0.0.1:${server.address().port}/challenge/join/ABCD-2345`);assert.equal(page.status,200);assert.match(await page.text(),/فتح في التطبيق/);const links=await fetch(`http://127.0.0.1:${server.address().port}/.well-known/assetlinks.json`);assert.equal(links.status,200);const data=await links.json();assert.equal(data[0].target.package_name,'com.elforma.elforma');});
 await test('owner creates a private friend challenge',async()=>{const r=await req('POST','/api/mobile/friend-challenges/create',{title:'تحدي خاص',kind:'custom',metric:'manual_daily',scoring:'daily',start,end,weekdays:[0,1,2,3,4,5,6],maxMembers:6},21);assert.equal(r.status,200);id=r.data.item.id;assert.equal((await req('GET','/api/mobile/friend-challenges',null,22)).data.items.length,0);});
 await test('member request stays pending until owner accepts',async()=>{const invite=await req('POST','/api/mobile/friend-challenges/invite',{id,maxUses:5},21);code=invite.data.invite.code;assert.equal((await req('GET','/api/mobile/friend-challenges/preview?code='+encodeURIComponent(code),null,22)).status,200);assert.equal((await req('POST','/api/mobile/friend-challenges/request',{code,displayName:'محمد'},22)).data.status,'pending');assert.equal((await req('GET','/api/mobile/friend-challenges',null,22)).data.items.length,0);assert.equal((await req('POST','/api/mobile/friend-challenges/decide',{id,userId:22,approve:true},21)).status,200);});
 await test('accepted member invites another and owner decides',async()=>{const invite=await req('POST','/api/mobile/friend-challenges/invite',{id,maxUses:2},22);assert.equal(invite.status,200);await req('POST','/api/mobile/friend-challenges/request',{code:invite.data.invite.code,displayName:'عمر'},23);assert.equal((await req('POST','/api/mobile/friend-challenges/decide',{id,userId:23,approve:true},22)).status,403);const accepted=await req('POST','/api/mobile/friend-challenges/decide',{id,userId:23,approve:true},21);assert.equal(accepted.data.item.participantCount,3);});
 await test('logging and closing return a stable leaderboard',async()=>{assert.equal((await req('POST','/api/mobile/friend-challenges/log',{id,value:true},22)).status,200);const closed=await req('POST','/api/mobile/friend-challenges/close',{id},21);assert.equal(closed.data.item.status,'closed');assert.equal(closed.data.item.finalResults[0].displayName,'محمد');});
 console.log(`${checks} friend challenge HTTP checks passed`);server.close(()=>{sql.close();fs.rmSync(process.env.EF_DATA_DIR,{recursive:true,force:true});process.exit(0);});
})().catch(error=>{console.error(error);server.close(()=>process.exit(1));});
