'use strict';
const assert=require('assert');
const http=require('http'),fs=require('fs'),path=require('path'),os=require('os');
process.env.EF_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'ef-phase23-'));process.env.PORT='0';
const server=require('../server'), db=require('../lib/db'), mobile=require('../api/mobile');
function req(method,p,body,cookie){return new Promise((resolve,reject)=>{const a=server.address(),raw=body==null?null:JSON.stringify(body),h={};if(raw){h['Content-Type']='application/json';h['Content-Length']=Buffer.byteLength(raw)}if(cookie)h.Cookie=cookie;const q=http.request({host:'127.0.0.1',port:a.port,method,path:p,headers:h},r=>{let x='';r.on('data',c=>x+=c);r.on('end',()=>{let j={};try{j=JSON.parse(x||'{}')}catch(e){};const sc=(r.headers['set-cookie']||[]).join(';'),m=/ef_session=[^;]*/.exec(sc);resolve({status:r.statusCode,json:j,cookie:m&&m[0]})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
(async()=>{
 await new Promise(r=>server.listening?r():server.on('listening',r));
 // Phase 2 pure contract: no invented explanation while collecting.
 const dx=require('../lib/plateau-diagnostics'), period=require('../lib/diet-periodization');
 const empty=mobile.buildDecisionExplanation({weights:[],loggedDays:0},dx.diagnose({goal:'cut',weights:[]}),period.autoAdjust({goal:'cut',targetCals:2000,maintenanceCals:2500,weights:[],week:1}),true);
 assert.strictEqual(empty.available,false);assert.strictEqual(empty.explanation,null);
 const weights=Array.from({length:21},(_,i)=>({date:new Date(Date.now()-(20-i)*86400000).toISOString().slice(0,10),weight:90}));
 const diagnosis=dx.diagnose({goal:'cut',weights,loggedDays:21,adherencePct:62,windowDays:21,dietWeeks:4});
 const explained=mobile.buildDecisionExplanation({weights,loggedDays:21,adherencePct:62,adherenceSource:'logged'},diagnosis,period.autoAdjust({goal:'cut',targetCals:2000,maintenanceCals:2500,weights,loggedDays:21,adherencePct:62,week:4}),true);
 assert.strictEqual(explained.explanation.causeKey,'adherence');assert.match(explained.explanation.findingAr,/62/);assert.strictEqual(explained.observed.adherencePct,62);
 assert.strictEqual(mobile.buildReadinessDecision({acwr:1,sleepHours:7,stress:1}).action,'normal');
 assert.strictEqual(mobile.buildReadinessDecision({acwr:1.8,sleepHours:5,stress:5}).zone,'low');
 assert.strictEqual(mobile.buildReadinessDecision({isRest:true}).action,'keep_rest');
 assert.strictEqual(mobile.buildReadinessDecision({acwr:null,sleepHours:8,fatigue:0,pain:0,readiness:0}).score,100);
 assert.strictEqual(mobile.buildReadinessDecision({sleepHours:7,fatigue:1,pain:0,readiness:0}).zone,'caution');
 assert.strictEqual(mobile.buildReadinessDecision({sleepHours:7,fatigue:0,pain:0,readiness:2}).zone,'low');
 assert.strictEqual(mobile.buildReadinessDecision({sleepHours:7,fatigue:0,pain:2,readiness:0}).zone,'low');
 const signup=await req('POST','/api/auth/signup',{email:`p23_${Date.now()}@gmail.com`,password:'supersecret123',name:'P23'});assert.strictEqual(signup.status,201);const c=signup.cookie;
 const plan=await req('PUT','/api/mobile/workout-plan',{key:'p23',plan:{key:'p23',name:'P23',plan:[{key:'train',name:'Train',exercises:[{name:'Barbell Bench Press'}]},{key:'rest',name:'Rest',isRest:true,exercises:[]},{key:'rest2',name:'Rest 2',isRest:true,exercises:[]},{key:'rest3',name:'Rest 3',isRest:true,exercises:[]},{key:'rest4',name:'Rest 4',isRest:true,exercises:[]},{key:'rest5',name:'Rest 5',isRest:true,exercises:[]},{key:'rest6',name:'Rest 6',isRest:true,exercises:[]}]}},c);assert.strictEqual(plan.status,200);
 const start=await req('POST','/api/mobile/session/start',{dayKey:'train',dayName:'Train'},c);assert.strictEqual(start.status,201);const sid=start.json.session.id;
 const beforeSessions=db.recentWorkoutSessions(signup.json.user.id,100).length,beforeWeights=db.recentWeights(signup.json.user.id,100).length;
 const beforePlan=await req('GET','/api/state',null,c);
 const pending=await req('GET',`/api/mobile/session/readiness?sessionId=${sid}`,null,c);
 assert.strictEqual(pending.json.status,'needs_checkin');assert.strictEqual(pending.json.readiness,null);
 assert.strictEqual(db.db.prepare('SELECT COUNT(*) AS n FROM session_readiness').get().n,0);
 const invalid=await req('POST','/api/mobile/session/readiness',{sessionId:sid,checkIn:{sleepHours:'7',fatigue:0,pain:0,readiness:0}},c);
 assert.strictEqual(invalid.status,422);
 const r1=await req('POST','/api/mobile/session/readiness',{sessionId:sid,checkIn:{sleepHours:7,fatigue:1,pain:0,readiness:0}},c);assert.strictEqual(r1.status,200);assert.strictEqual(r1.json.readiness.decision.sessionOnly,true);assert.strictEqual(r1.json.readiness.decision.planMutation,false);assert.ok(r1.json.readiness.source.training);assert.ok(r1.json.readiness.explanation);
 assert.strictEqual(r1.json.readiness.decision.zone,'caution');
 assert.strictEqual(r1.json.readiness.decision.setMultiplier,.75);
 assert.deepStrictEqual((await req('GET','/api/state',null,c)).json,beforePlan.json);
 const r2=await req('POST','/api/mobile/session/readiness',{sessionId:sid},c);assert.strictEqual(r2.status,200);assert.strictEqual(r2.json.idempotent,true);assert.strictEqual(r2.json.readiness.createdAt,r1.json.readiness.createdAt);
 const r3=await req('GET','/api/mobile/session/readiness',null,c);assert.strictEqual(r3.status,200);assert.strictEqual(r3.json.readiness.sessionId,sid);
 assert.strictEqual(db.recentWorkoutSessions(signup.json.user.id,100).length,beforeSessions);assert.strictEqual(db.recentWeights(signup.json.user.id,100).length,beforeWeights);
 const changedAnswer=await req('POST','/api/mobile/session/readiness',{sessionId:sid,checkIn:{sleepHours:5,fatigue:2,pain:2,readiness:2}},c);
 assert.strictEqual(changedAnswer.json.readiness.decision.zone,'caution');
 const finish=await req('POST','/api/mobile/session/finish',{sessionId:sid,durationSec:10,notes:''},c);assert.strictEqual(finish.status,200);
 const next=await req('GET','/api/mobile/session/readiness',null,c);assert.strictEqual(next.status,200);assert.strictEqual(next.json.dayReset,true);assert.strictEqual(next.json.readiness,null);
 const other=await req('POST','/api/auth/signup',{email:`p23b_${Date.now()}@gmail.com`,password:'supersecret123',name:'P23B'});assert.strictEqual(other.status,201);
 const foreign=await req('GET',`/api/mobile/session/readiness?sessionId=${sid}`,null,other.cookie);assert.strictEqual(foreign.status,200);assert.strictEqual(foreign.json.readiness,null);
 const past=new Date(Date.now()-172800000).toISOString();
 db.db.prepare('UPDATE workout_sessions SET started_at=?,finished_at=? WHERE id=?').run(past,past,sid);
 const newSession=await req('POST','/api/mobile/session/start',{dayKey:'train',dayName:'Train'},c);
 assert.notStrictEqual(newSession.json.session.id,sid);
 assert.strictEqual((await req('GET','/api/mobile/session/readiness',null,c)).json.status,'needs_checkin');
 const low=await req('POST','/api/mobile/session/readiness',{sessionId:newSession.json.session.id,checkIn:{sleepHours:5,fatigue:2,pain:0,readiness:2}},c);
 assert.strictEqual(low.json.readiness.decision.zone,'low');
 assert.strictEqual(low.json.readiness.decision.setMultiplier,.5);
 console.log('Phase 2/3 contract, readiness answers, idempotency, reset, isolation and non-mutation passed');
 server.close(()=>process.exit(0));
})().catch(e=>{console.error(e);server.close(()=>process.exit(1))});
