'use strict';
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.EF_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'ef-progress-story-'));process.env.PORT='0';
const server=require('../server'),db=require('../lib/db'),progress=require('../lib/progress-events');
function request(method,pathname,body,cookie){return new Promise((resolve,reject)=>{const a=server.address(),raw=body==null?null:JSON.stringify(body),h={};if(raw){h['Content-Type']='application/json';h['Content-Length']=Buffer.byteLength(raw)}if(cookie)h.Cookie=cookie;const req=http.request({host:'127.0.0.1',port:a.port,method,path:pathname,headers:h},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>{let json={};try{json=JSON.parse(text||'{}')}catch(_){}const m=/ef_session=[^;]*/.exec((res.headers['set-cookie']||[]).join(';'));resolve({status:res.statusCode,json,cookie:m&&m[0]})})});req.on('error',reject);if(raw)req.write(raw);req.end()})}
function day(n){return new Date(Date.now()+n*86400000).toISOString().slice(0,10)}
function time(n){return new Date(Date.now()+n*86400000).toISOString()}
function session(uid,n,w){const s=db.startWorkoutSessionOnce(uid,null,'story-'+n,'Story',time(n));db.saveWorkoutSet({sessionId:s.id,exerciseKey:'bench_press',exerciseName:'Bench Press',setNumber:1,weight:w,reps:5,rir:2,completed:true});db.finishWorkoutSession(s.id,uid,time(n),1200,'test');return s.id}
(async()=>{await new Promise(r=>server.listening?r():server.on('listening',r));const a=await request('POST','/api/auth/signup',{email:`story_a_${Date.now()}@gmail.com`,password:'supersecret123',name:'Story A'}),b=await request('POST','/api/auth/signup',{email:`story_b_${Date.now()}@gmail.com`,password:'supersecret123',name:'Story B'});assert.equal(a.status,201);assert.equal(b.status,201);const uid=a.json.user.id,month=day(0).slice(0,7);db.saveMobileProfile(uid,JSON.stringify({weight:100,targetWeight:90,targetCals:2000}));db.saveWeight(uid,day(-6),100,null);db.saveWeight(uid,day(-5),99,null);db.saveWeight(uid,day(-4),95,null);db.saveWeight(uid,day(-3),90,null);const ids=[];for(let i=1;i<=5;i++)ids.push(session(uid,-i,70+i*5));let story=progress.story(uid,month),types=story.events.map(e=>e.type);assert.equal(story.summary.sessions,5);assert.equal(story.summary.weightStart,100);assert.equal(story.summary.weightEnd,90);assert(types.includes('new_pr'));assert(types.includes('training_consistency'));assert(types.includes('weight_milestone'));assert.equal(new Set(story.events.map(e=>e.eventKey)).size,story.events.length);const again=progress.story(uid,month);assert.equal(again.events.length,story.events.length);const moment=story.moments[0].id;progress.markSeen(uid,[moment,moment]);assert.equal(progress.story(uid,month).moments.some(e=>e.id===moment),false);db.db.prepare('DELETE FROM workout_sessions WHERE id=?').run(ids[4]);assert.equal(progress.story(uid,month).events.some(e=>e.sourceId===String(ids[4])),false);const apiA=await request('GET','/api/mobile/progress-story',null,a.cookie),apiB=await request('GET','/api/mobile/progress-story',null,b.cookie);assert.equal(apiA.status,200);assert.equal(apiB.status,200);assert.equal(apiB.json.empty,true);assert.equal(apiB.json.events.length,0);const foreign=await request('POST','/api/mobile/progress-story/ack',{ids:[moment]},b.cookie);assert.equal(foreign.status,200);assert.equal(progress.story(uid,month).events.find(e=>e.id===moment)?.seenAt!=null,false);console.log('Progress Story event projection, idempotency, reconciliation, API and account isolation passed');server.close(()=>process.exit(0))})().catch(e=>{console.error(e);server.close(()=>process.exit(1))});
