'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const read=p=>fs.readFileSync(require('node:path').join(__dirname,'..',p),'utf8');
const manifest=read('mobile/android/app/src/main/AndroidManifest.xml');
const main=read('mobile/android/app/src/main/kotlin/com/elforma/elforma/MainActivity.kt');
const service=read('mobile/android/app/src/main/kotlin/com/elforma/elforma/StepTrackingService.kt');
const store=read('mobile/android/app/src/main/kotlin/com/elforma/elforma/StepTrackingStore.kt');
const home=read('mobile/lib/widgets/community_home.dart');
const steps=read('mobile/lib/screens/steps_screen.dart');
const completion=read('mobile/lib/screens/home_screen.dart');
assert(manifest.includes('.StepTrackingService')&&manifest.includes('foregroundServiceType="health"'));
assert(manifest.includes('FOREGROUND_SERVICE_HEALTH')&&manifest.includes('.StepTrackingBootReceiver'));
assert(service.includes('START_STICKY'));
assert(service.includes('Sensor.TYPE_STEP_COUNTER')&&service.includes('Sensor.TYPE_STEP_DETECTOR'));
assert(store.includes('tracking_start_date')&&store.includes('day_count:'));
assert(store.includes('if (prefs.contains(COUNTER_TOTAL))'));
assert(/else\s+total\.roundToInt\(\)/.test(store));
assert(store.includes('.putString("last_event_date", today.toString())'));
assert(main.includes('readLocal')&&main.includes('trackingStart'));
assert(home.includes("invokeMapMethod<String, dynamic>('readLocal')"));
assert(home.includes('Duration(minutes: 1)'));
const stepsCard=home.slice(home.indexOf('Widget _stepsCard()'),home.indexOf('Widget _challengeCard('));
const challengeCard=home.slice(home.indexOf('Widget _challengeCard('),home.indexOf('Widget _kitchenCard()'));
assert(!stepsCard.includes('chevron_left_rounded'));
assert(!challengeCard.includes('chevron_left_rounded'));
assert(challengeCard.includes('active.length')&&challengeCard.includes('CommunityScreen()'));
assert(steps.includes('if (days.length > 1)')&&steps.includes('منذ بدء التتبع'));
const copy='استمرارك النهارده بيقربك من هدفك ريح عضلاتك وكمل أكلك ومياهك وبكرة نكمل أقوى';
assert(completion.includes(copy));assert(!/[،,.]/.test(copy));
console.log('background/offline steps, multiple challenges, card and copy contracts passed');
