// Catalog movement-family profiles. These are deliberately tracking-only.
// They count visible movement and phases but do not claim full form correction.
import 'package:elforma/features/form_coach/domain/fc_landmarks.dart';
import 'package:elforma/features/form_coach/domain/form_profile.dart';
import 'package:elforma/features/form_coach/domain/metric_spec.dart';
import 'package:elforma/features/form_coach/domain/readiness.dart';
import 'package:elforma/features/form_coach/domain/rep_cycle.dart';

FormProfile _catalogTracking(
    String id,
    String title,
    List<String> names,
    List<FcJoint> joints,
    double top,
    double bottom,
    String topLabel,
    String bottomLabel,
    {MetricKind kind = MetricKind.jointAngle}) {
  return FormProfile(
    id: id,
    titleAr: title,
    supportLevel: FormSupportLevel.trackingOnly,
    setupHintAr: 'ثبّت الهاتف وأظهر المفاصل المطلوبة بالكامل',
    detectableAr: <String>['العداد التقريبي', 'مرحلة الحركة', 'المدى الظاهر'],
    notDetectableAr: <String>[
      'الوزن والقبضة',
      'شد العضلة والتنفس',
      'التفاصيل خارج زاوية التصوير'
    ],
    matchKeywords: names,
    completion: const CompletionSpec(fallbackTargetReps: 10),
    variants: <FormProfileVariant>[
      FormProfileVariant(
        id: '$id.default',
        titleAr: '$title - متابعة الحركة',
        supportLevel: FormSupportLevel.trackingOnly,
        readiness: ReadinessSpec(
            requiredJoints: joints,
            minTorsoFraction: 0.08,
            maxTorsoFraction: 0.85),
        sideSelection: SideSelection.activeSide,
        sideAmplitudeMetrics: const ['motion_left', 'motion_right'],
        metrics: <MetricSpec>[
          for (final entry in {
            'motion_left': MetricSide.left,
            'motion_right': MetricSide.right
          }.entries)
            MetricSpec(
                id: entry.key,
                kind: kind,
                side: entry.value,
                joints: kind == MetricKind.limbAbductionFromTorso
                    ? joints.sublist(0, 2)
                    : joints.sublist(0, 3)),
          MetricSpec(
            id: 'movement_angle',
            kind: kind,
            joints: kind == MetricKind.limbAbductionFromTorso
                ? joints.sublist(0, 2)
                : joints.sublist(0, 3),
            side: MetricSide.activeSide,
            labelAr: 'زاوية الحركة',
          )
        ],
        repCycle: RepCycleSpec(
            driverMetricId: 'movement_angle',
            topValue: top,
            bottomValue: bottom,
            enterMargin: 18,
            minAmplitude: 30,
            partialAmplitude: 18,
            topLabelAr: topLabel,
            bottomLabelAr: bottomLabel),
        driverMinConfidence: 0.52,
      ),
    ],
  );
}

final List<FormProfile> catalogFormProfiles = <FormProfile>[
  _catalogTracking(
      'catalog_upper_family',
      'تمارين الجزء العلوي',
      <String>[
        'Incline Dumbbell Press',
        'Incline Smith Machine Press',
        'Low to High Cable Fly',
        'Barbell Bench Press',
        'Dumbbell Bench Press',
        'Machine Chest Press',
        'Smith Machine Flat Press',
        'Cable Chest Press',
        'Pec Deck Machine',
        'Seated Cable Fly',
        'Dips (Chest Variation)',
        'Decline Barbell Press',
        'Decline Dumbbell Press',
        'High to Low Cable Fly',
        'Decline Cable Fly',
        'Machine Shoulder Press',
        'Seated DB Shoulder Press',
        'Overhead Barbell Press',
        'Smith Machine Shoulder Press',
        'Overhead Cable Tricep Extension',
        'Skull Crushers (EZ Bar)',
        'Dumbbell Overhead Tricep Ext',
        'Rope Tricep Pushdown',
        'Bar Tricep Pushdown',
        'Cable Tricep Kickback',
        'Katana Extension',
        'Tricep Dips Machine',
        'Cable Hip Adduction',
        'Seated Hip Adduction Machine',
        'Incline Push-Up (Elevated Surface)',
        'Wide Push-Up',
        'Resistance Band Chest Fly',
        'Decline Push-Up (Feet Elevated)',
        'Dumbbell Shoulder Press (Seated)',
        'Pike Push-Up',
        'DB Overhead Tricep Extension',
        'Resistance Band Pushdown',
        'Close Grip Push-Up',
      ],
      <FcJoint>[FcJoint.shoulder, FcJoint.elbow, FcJoint.wrist],
      165,
      78,
      'الوضع الممدود',
      'نهاية الحركة'),
  _catalogTracking(
      'catalog_pull_family',
      'السحب والرو',
      <String>[
        'Lat Pullover Machine',
        'Cable Pullover',
        'Barbell Bent Over Row',
        'Chest Supported Row Machine',
        'Seated Cable Row',
        'Meadows Row',
        'One Arm Dumbbell Row',
        'Wide Grip Seated Row',
        'Smith Machine Row',
        'One Hand Cable Row',
        'Single Arm Cable Row',
        'Single Arm DB Row (Chair)',
        'Resistance Band Seated Row',
      ],
      <FcJoint>[FcJoint.shoulder, FcJoint.elbow, FcJoint.wrist],
      165,
      75,
      'الذراع ممدودة',
      'نهاية السحب'),
  _catalogTracking(
      'catalog_lower_family',
      'الرجلين والهينج',
      <String>[
        'Barbell Back Squat',
        'Hack Squat Machine',
        'Smith Machine Squat',
        'Pendulum Squat',
        'Leg Press (45°)',
        'Front Barbell Squat',
        'Bulgarian Split Squat',
        'Walking Lunges (Barbell)',
        'Step-Up with Barbell',
        'Sissy Squat',
        'Leg Press Narrow Stance',
        'Standing Calf Raise (Machine)',
        'Smith Machine Calf Raise',
        'Leg Press Calf Raise',
        'Donkey Calf Raise',
        'Seated Calf Raise Machine',
        'Dumbbell Side Lunge',
        'Goblet Squat (Dumbbell)',
        'Bulgarian Split Squat (Chair)',
        'Resistance Band Squat',
        'Step-Up (Chair/Box)',
        'Standing Calf Raise (BW)',
        'Single Leg Calf Raise',
      ],
      <FcJoint>[FcJoint.hip, FcJoint.knee, FcJoint.ankle],
      168,
      88,
      'الوضع العالي',
      'نهاية النزول'),
  _catalogTracking(
      'catalog_raise_family',
      'الرفعات والترابيس',
      <String>[
        'Cable Upper Chest Crossover',
        'Rope Face Pull',
        'Reverse Cable Crossover',
        'Rear Delt Machine Fly',
        'Cable Rear Delt Fly',
        'Bent Over Rear Delt Raise',
        'Barbell Shrugs',
        'Smith Machine Shrugs',
        'Dumbbell Shrugs',
        'Resistance Band Face Pull',
        'Prone Dumbbell Y-Raise',
        'Side Lying DB Raise',
        'Dumbbell Rear Delt Fly',
      ],
      <FcJoint>[FcJoint.shoulder, FcJoint.elbow, FcJoint.hip],
      15,
      82,
      'الذراع منخفضة',
      'الذراع مرفوعة',
      kind: MetricKind.limbAbductionFromTorso),
  _catalogTracking(
      'catalog_core_family',
      'تمارين الكور',
      <String>[
        'Cable Crunch',
        'Ab Wheel Rollout',
        'Hanging Leg Raise',
        'Cable Woodchop',
        'Decline Sit-Up',
        'Hanging Leg Raise (Pull-Up Bar)',
        'Bicycle Crunch',
      ],
      <FcJoint>[FcJoint.shoulder, FcJoint.hip, FcJoint.knee],
      165,
      95,
      'الوضع الممتد',
      'نهاية الحركة'),
  _catalogTracking(
      'catalog_hinge_family',
      'حركة مفصل الورك',
      <String>[
        'Lower Back Extensions',
        'Single Leg RDL (Dumbbell)',
        'Romanian Deadlift',
        'Stiff Leg Deadlift',
        'Romanian Deadlift (RDL)',
        'Stiff-Leg Deadlift',
        'Barbell Hip Thrust',
        'Cable Pull Through',
        'Smith Machine Hip Thrust',
        'Dumbbell Romanian Deadlift',
        'Glute Bridge Weighted',
        'Resistance Band Pull Through',
      ],
      <FcJoint>[FcJoint.shoulder, FcJoint.hip, FcJoint.knee],
      168,
      100,
      'الورك ممدود',
      'نهاية ثني الورك'),
];
