#!/usr/bin/env python3
"""Patch the Android app module generated by `flutter create` so the release
build actually succeeds.

Why this file exists
--------------------
`flutter_local_notifications` (our workout / meal / water / weight reminders)
uses java.time APIs that do not exist on older Android API levels. The Android
Gradle Plugin can back-port them, but only when "core library desugaring" is
turned on explicitly. `flutter create` never turns it on, so a release build
dies with:

    Dependency ':flutter_local_notifications' requires core library
    desugaring to be enabled for :app.

The android/ folder is generated fresh inside CI on every run, so this patch
has to be applied on every build instead of being committed once.

It handles both the Kotlin DSL (build.gradle.kts, current Flutter templates)
and the older Groovy DSL (build.gradle), and it exits non-zero if it cannot
apply the patch -- a silent failure here would just move the error further
down the build.
"""

import re
import sys
from pathlib import Path

DESUGAR_VERSION = "2.1.4"


def find_build_file() -> Path:
    for name in ("build.gradle.kts", "build.gradle"):
        candidate = Path("android/app") / name
        if candidate.is_file():
            return candidate
    sys.exit("FAIL: android/app/build.gradle[.kts] not found -- did flutter create run?")


def ensure_java_11(text: str, kts: bool) -> str:
    """desugar_jdk_libs 2.x needs Java 11 source/target compatibility."""
    return text.replace("JavaVersion.VERSION_1_8", "JavaVersion.VERSION_11")


def ensure_compile_options(text: str, kts: bool) -> str:
    """Add coreLibraryDesugaringEnabled inside the compileOptions block."""
    # Case-insensitive on purpose: the Kotlin DSL property is
    # `isCoreLibraryDesugaringEnabled` while Groovy uses
    # `coreLibraryDesugaringEnabled`. A case-sensitive check missed the Kotlin
    # spelling and appended the flag a second time on re-runs.
    if "corelibrarydesugaringenabled" in text.lower():
        return text

    flag = (
        "        isCoreLibraryDesugaringEnabled = true\n"
        if kts
        else "        coreLibraryDesugaringEnabled true\n"
    )

    match = re.search(r"compileOptions\s*\{\s*\n", text)
    if match:
        return text[: match.end()] + flag + text[match.end() :]

    # No compileOptions block at all: create one right inside `android { ... }`.
    block = (
        "    compileOptions {\n"
        + flag
        + (
            "        sourceCompatibility = JavaVersion.VERSION_11\n"
            "        targetCompatibility = JavaVersion.VERSION_11\n"
            if kts
            else "        sourceCompatibility JavaVersion.VERSION_11\n"
            "        targetCompatibility JavaVersion.VERSION_11\n"
        )
        + "    }\n\n"
    )
    android = re.search(r"\nandroid\s*\{\s*\n", text)
    if not android:
        sys.exit("FAIL: no `android { }` block found in the Gradle file")
    return text[: android.end()] + block + text[android.end() :]


def ensure_desugar_dependency(text: str, kts: bool) -> str:
    """Add the desugar_jdk_libs artifact that does the actual back-porting."""
    if "desugar_jdk_libs" in text:
        return text

    coord = "com.android.tools:desugar_jdk_libs:" + DESUGAR_VERSION
    line = (
        '    coreLibraryDesugaring("' + coord + '")\n'
        if kts
        else "    coreLibraryDesugaring '" + coord + "'\n"
    )

    # Prefer an existing top-level dependencies block.
    match = re.search(r"\ndependencies\s*\{\s*\n", text)
    if match:
        return text[: match.end()] + line + text[match.end() :]

    return text.rstrip() + "\n\ndependencies {\n" + line + "}\n"


def main() -> None:
    path = find_build_file()
    kts = path.suffix == ".kts"
    original = path.read_text(encoding="utf-8")

    patched = ensure_java_11(original, kts)
    patched = ensure_compile_options(patched, kts)
    patched = ensure_desugar_dependency(patched, kts)

    if patched == original:
        print("NOTE: " + str(path) + " already had desugaring enabled")
    else:
        path.write_text(patched, encoding="utf-8")
        print("PATCHED: " + str(path) + (" (Kotlin DSL)" if kts else " (Groovy DSL)"))

    # Verify rather than trust: a wrong patch must fail here, not at Gradle time.
    final = path.read_text(encoding="utf-8")
    problems = []
    if "CoreLibraryDesugaringEnabled" not in final and "coreLibraryDesugaringEnabled" not in final:
        problems.append("coreLibraryDesugaringEnabled flag missing")
    if "desugar_jdk_libs" not in final:
        problems.append("desugar_jdk_libs dependency missing")
    if problems:
        sys.exit("FAIL: " + "; ".join(problems))

    print("VERIFIED: core library desugaring is enabled")
    print("---- " + str(path) + " ----")
    print(final)


if __name__ == "__main__":
    main()